url: "https://domkolp.qzz.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Dominic Kolp" # the name of your site, e.g. ACME Corp.
language: en-US

include:
  - pages

collections:
  projects:
    output: true
    permalink: /projects/:path/
  policies:
    output: true
    permalink: /policies/:path/

username: stupidlilgoober
email: contact@domkolp.qzz.io
github: stupidlilgoober
youtube: stupid-dev
discord: stupidlilgoober
